[package]
name = "rs-signer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.8"
ethers-core = "2.0.8"
hex = "0.4.3"
tokio = { version = "1.31.0", features = ["full"] }
